apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
  namespace: production
  labels:
    app: mysql-db
spec:
  containers:
  - name: mysql-db
    image: mysql
    ports:
      - containerPort: 8080
    env:
      - name: MYSQL_DATABASE
        value: eazytraining
      - name: MYSQL_USER
        value: eazy
      - name: MYSQL_PASSWORD
        value: eazy
      - name: MYSQL_ROOT_PASSWORD
        value: password
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-datas
  
  volumes:
  - name: mysql-datas
    hostPath:
       path: /data-volume
       type: Directory

